# Generated by Django 3.2.9 on 2021-11-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_answer',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
