# Generated by Django 3.2.9 on 2021-11-17 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20211117_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 5, 29, 0, 891207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 5, 29, 0, 501559, tzinfo=utc)),
        ),
    ]
