# Generated by Django 3.2.9 on 2021-11-17 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20211117_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 5, 30, 15, 676097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 5, 30, 15, 391967, tzinfo=utc)),
        ),
    ]
